trigger:
  branches:
    include:
      - release

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: none

  - task: SSH@0
    displayName: "🔐  Connect via SSH & Deploy"
    inputs:
      sshEndpoint: "Kitty Server (Miku)"
      runOptions: inline
      inline: |
        echo "🔑  Step 1: connecting nvm"
        export NVM_DIR="$HOME/.nvm"
        # если nvm установлен через стандартный инсталлятор:
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        # подхватить нужную версию Node (можно заменить на вашу)
        nvm use 22.18.0

        echo "📥  Step 2: updating repo"
        cd /home/miku/miku-renderer
        git pull --quiet origin release

        echo "📦  Step 3: installing deps"
        npm install

        echo "🏗️  Step 4: building project"
        npm run build

        echo "🔄  Step 5: pm2 restart"
        pm2 restart renderer

        echo "✅  Deployment on branch release completed successfully"
